### ISSUE TITLE
To-Do's

### ISSUE THREAD

**Issue by juanjucm** [juanjucm/finetuning-mlms#1]
- [x] Retrain every model and upload artifacts.
- [x] Improve technical documentation. Include created diagrams in README.
- [x] Further explain the results.
- [x] Include dataset partition numbers and training parameters in Experiment Setup section.
- [x] Include references section.
- [x] Refactor repo name.
- [ ] Create src scripts for automatic fine-tuning (following the workflow) given a dataset.
